### Задание 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np

In [2]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [7]:
n = len(X)
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [8]:
a = np.mean(y) - b * np.mean(X)
a

444.1773573243596

Без интерсепта

In [10]:
X = X.reshape((10,1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [11]:
y = y.reshape((10,1))
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [12]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @ y)
B

array([[5.88982042]])

С интерсептом

In [13]:
X = np.hstack([np.ones((10,1)),X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [14]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

### Задание 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [33]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
n = len(X)

In [34]:
B1 = 0.1
alpha= 1e-6

def mse_ (B1,y=y,X=X,n=n):
    return np.sum((B1*X-y)**2)/n

for i in range(3000):
    B1 -= alpha * (2/n)*np.sum((B1*X-y)*X)
    if i%1000 == 0:
        print(f"B1 = {B1},mse = {mse_(B1)},iter = {i}")

B1 = 0.25952808,mse = 493237.7212546963,iter = 0
B1 = 5.8898204201285544,mse = 56516.85841571941,iter = 1000
B1 = 5.889820420132673,mse = 56516.85841571943,iter = 2000


In [45]:
B1 = 0.1
B0 = 0.1
alpha = 5e-5

In [46]:
def mse__(B0,B1,y=y,X=X,n=n):
    return np.sum((B0+B1*X-y)**2)/n

In [47]:
for i in range(3000000):
    y_pred = B0+B1*X
    B0 -= alpha*(2/n)*np.sum((y_pred-y))
    B1 -= alpha*(2/n)*np.sum((y_pred-y)*X)
    if i%300000 == 0:
        print(f"B0 = {B0},B1 = {B1},mse = {mse__(B0,B1)},iter = {i}")

B0 = 0.169966,B1 = 8.07539,mse = 122360.8044853729,iter = 0
B0 = 443.9572751113981,B1 = 2.6221587847940984,mse = 6470.426487736031,iter = 300000
B0 = 444.177248239628,B1 = 2.6205396853146192,mse = 6470.414201179677,iter = 600000
B0 = 444.1773572702843,B1 = 2.620538882800784,mse = 6470.41420117666,iter = 900000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 1200000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 1500000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 1800000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 2100000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 2400000
B0 = 444.17735732323933,B1 = 2.6205388824110107,mse = 6470.414201176658,iter = 2700000


### Задание 3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента? 

Таблица Стьюдента используется когда не известна дисперсия